### ISSUE TITLE
Override path

### ISSUE THREAD

**Issue by DeNIKE666** [outer-web/image-library#1]
Hi, how can I override the path for a user to stack all images by their id e.g. /app/public/user/1/ I couldn't find documentation on how to override the path

**Comment by SimonBroekaert** [comment]
Hi,

I think that, what you are trying to achieve, is possible like this:

1. Create your own Image model class that extends the one of this package.
2. Override the `getBasePath()` method ([this one](https://github.com/outer-web/image-library/blob/main/src/Models/Image.php#L67)) of the model class wit your own implementation
3. Update the config/image-library.php file so that the package uses your custom model [here](https://github.com/outer-web/image-library/blob/main/config/image-library.php#L8)

Hope you can achieve it like that!

Kind regards

**Comment by SimonBroekaert** [comment]
Hi @DeNIKE666 ,

As I have not yet heard back of you, I will mark the issue/question as closed.

You can always re-open it if needed!

Thanks
