### ISSUE TITLE
TextInput::translatable does not exist.

### ISSUE THREAD

**Issue by pMatt1988** [outer-web/image-library#2]
Hello, after I followed the instructions to install your plugin and try to upload a new image from the image library I get the following error
```Method Filament\Forms\Components\TextInput::translatable does not exist.```

I'm using Laravel 11.0.8, FilamentPHP v3.2.58 and filament-image-library v2.3.0

**Comment by pMatt1988** [comment]
I solved this by installing the Filament Translatable Fields plugin.

**Comment by SimonBroekaert** [comment]
Hi @pMatt1988 ,

Thanks again for reporting this!

It is indeed required to setup the Filament Translatable Fields plugin of ours. But it should not break your application ofcourse. I have therefor added checks before using the `translatable()` method on fields to see if the translatable fields plugin is installed on the current dashboard. I have also updated the Readme to provide more information about using the translations.

You can use the solution by upgrading to **v2.4.0**

See [the changelog](https://github.com/outer-web/filament-image-library/blob/main/CHANGELOG.md) of the filament-image-library as the issue is only present in the filament plugin.

I will mark this as solved, but feel free te re-open if needed!
